// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"time"

	"github.com/google/uuid"
)

type EventsEvent struct {
	ID          uuid.UUID `json:"id"`
	Title       string    `json:"title"`
	Description *string   `json:"description"`
	Location    *string   `json:"location"`
	StartsAtUtc time.Time `json:"starts_at_utc"`
	EndsAtUtc   time.Time `json:"ends_at_utc"`
	Status      string    `json:"status"`
}
