// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/llannillo/mm/modules/events/internal/domain"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events.events (id, title, description, location, starts_at_utc, ends_at_utc, status)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type CreateEventParams struct {
	ID          uuid.UUID          `json:"id"`
	Title       string             `json:"title"`
	Description *string            `json:"description"`
	Location    *string            `json:"location"`
	StartsAtUtc time.Time          `json:"starts_at_utc"`
	EndsAtUtc   time.Time          `json:"ends_at_utc"`
	Status      domain.EventStatus `json:"status"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.StartsAtUtc,
		arg.EndsAtUtc,
		arg.Status,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getEvent = `-- name: GetEvent :one
SELECT id, title, description, location, starts_at_utc, ends_at_utc
FROM events.events
WHERE id = $1
`

type GetEventRow struct {
	ID          uuid.UUID `json:"id"`
	Title       string    `json:"title"`
	Description *string   `json:"description"`
	Location    *string   `json:"location"`
	StartsAtUtc time.Time `json:"starts_at_utc"`
	EndsAtUtc   time.Time `json:"ends_at_utc"`
}

func (q *Queries) GetEvent(ctx context.Context, id uuid.UUID) (GetEventRow, error) {
	row := q.db.QueryRow(ctx, getEvent, id)
	var i GetEventRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.StartsAtUtc,
		&i.EndsAtUtc,
	)
	return i, err
}
